- name: Add twofishesservers user
  user: name={{twofishes_user}}

- name: Add folders
  sudo_user: "{{twofishes_user}}"
  file: path={{twofishes_dir}}/logs/ state=directory recurse=yes

- name: Download twofishes server
  sudo_user: "{{twofishes_user}}"
  get_url: url={{twofishes_jar_url}}{{twofishes_jar_name}} dest={{twofishes_dir}}/{{twofishes_jar_name}}

- name: symlink jar file
  sudo_user: "{{twofishes_user}}"
  file: src={{twofishes_dir}}/{{twofishes_jar_name}} dest={{twofishes_dir}}/twofishes-server-current.jar state=link

- name: Download twofishes index 
  sudo_user: "{{twofishes_user}}"
  get_url: url={{twofishes_index_zip_url}}{{twofishes_index_zip_name}} dest={{twofishes_dir}}/{{twofishes_index_zip_name}}

- name: Unzip index
  sudo_user: "{{twofishes_user}}"
  shell: unzip {{twofishes_dir}}/{{twofishes_index_zip_name}} -d {{twofishes_dir}}/
  args:
    creates: "{{twofishes_dir}}/latest"

- name: Add init.d file for twofishes
  template:
    src=twofishes_init_d.j2
    dest=/etc/init.d/twofishes
    owner=root group=root mode=0755

- name: Add twofishes init.d to defaults
  shell: update-rc.d twofishes defaults

- name: twofishes-restart
  service: name=twofishes state=restarted